name: Generate Trophy
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Generate Trophy SVG
        uses: soulteary/github-profile-trophy-action@main
        with:
          options: "?username=sindresorhus&theme=tokyonight&no-bg=true&margin-w=4"
          path: "dist/trophy.svg"
          
      - name: Commit and push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist/trophy.svg
          git commit -m "chore: generate fake trophy svg" || echo "No changes"
          git push
